/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as LibraryIndexImport } from './routes/library/index'
import { Route as EditIndexImport } from './routes/edit/index'
import { Route as SearchAnimeIndexImport } from './routes/search/anime/index'
import { Route as DataAnimeIndexImport } from './routes/data/anime/index'

// Create Virtual Routes

const SignupIndexLazyImport = createFileRoute('/signup/')()
const SearchIndexLazyImport = createFileRoute('/search/')()
const LogoutIndexLazyImport = createFileRoute('/logout/')()
const LoginIndexLazyImport = createFileRoute('/login/')()
const GetstartedIndexLazyImport = createFileRoute('/getstarted/')()
const DataIndexLazyImport = createFileRoute('/data/')()
const LibraryDetailProgressIdLazyImport = createFileRoute(
  '/library/detail/$progressId',
)()
const EditAnimeAnimeIdLazyImport = createFileRoute('/edit/anime/$animeId')()
const ContentsAnimeAnimeIdLazyImport = createFileRoute(
  '/contents/anime/$animeId',
)()
const EditNewAnimeIndexLazyImport = createFileRoute('/edit/new/anime/')()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SignupIndexLazyRoute = SignupIndexLazyImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signup/index.lazy').then((d) => d.Route))

const SearchIndexLazyRoute = SearchIndexLazyImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/search/index.lazy').then((d) => d.Route))

const LogoutIndexLazyRoute = LogoutIndexLazyImport.update({
  id: '/logout/',
  path: '/logout/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/logout/index.lazy').then((d) => d.Route))

const LoginIndexLazyRoute = LoginIndexLazyImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login/index.lazy').then((d) => d.Route))

const GetstartedIndexLazyRoute = GetstartedIndexLazyImport.update({
  id: '/getstarted/',
  path: '/getstarted/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/getstarted/index.lazy').then((d) => d.Route),
)

const DataIndexLazyRoute = DataIndexLazyImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/data/index.lazy').then((d) => d.Route))

const LibraryIndexRoute = LibraryIndexImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRoute,
} as any)

const EditIndexRoute = EditIndexImport.update({
  id: '/edit/',
  path: '/edit/',
  getParentRoute: () => rootRoute,
} as any)

const SearchAnimeIndexRoute = SearchAnimeIndexImport.update({
  id: '/search/anime/',
  path: '/search/anime/',
  getParentRoute: () => rootRoute,
} as any)

const DataAnimeIndexRoute = DataAnimeIndexImport.update({
  id: '/data/anime/',
  path: '/data/anime/',
  getParentRoute: () => rootRoute,
} as any)

const LibraryDetailProgressIdLazyRoute =
  LibraryDetailProgressIdLazyImport.update({
    id: '/library/detail/$progressId',
    path: '/library/detail/$progressId',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/library/detail/$progressId.lazy').then((d) => d.Route),
  )

const EditAnimeAnimeIdLazyRoute = EditAnimeAnimeIdLazyImport.update({
  id: '/edit/anime/$animeId',
  path: '/edit/anime/$animeId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/edit/anime/$animeId.lazy').then((d) => d.Route),
)

const ContentsAnimeAnimeIdLazyRoute = ContentsAnimeAnimeIdLazyImport.update({
  id: '/contents/anime/$animeId',
  path: '/contents/anime/$animeId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/contents/anime/$animeId.lazy').then((d) => d.Route),
)

const EditNewAnimeIndexLazyRoute = EditNewAnimeIndexLazyImport.update({
  id: '/edit/new/anime/',
  path: '/edit/new/anime/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/edit/new/anime/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/edit/': {
      id: '/edit/'
      path: '/edit'
      fullPath: '/edit'
      preLoaderRoute: typeof EditIndexImport
      parentRoute: typeof rootRoute
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryIndexImport
      parentRoute: typeof rootRoute
    }
    '/data/': {
      id: '/data/'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/getstarted/': {
      id: '/getstarted/'
      path: '/getstarted'
      fullPath: '/getstarted'
      preLoaderRoute: typeof GetstartedIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/logout/': {
      id: '/logout/'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/contents/anime/$animeId': {
      id: '/contents/anime/$animeId'
      path: '/contents/anime/$animeId'
      fullPath: '/contents/anime/$animeId'
      preLoaderRoute: typeof ContentsAnimeAnimeIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/edit/anime/$animeId': {
      id: '/edit/anime/$animeId'
      path: '/edit/anime/$animeId'
      fullPath: '/edit/anime/$animeId'
      preLoaderRoute: typeof EditAnimeAnimeIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/library/detail/$progressId': {
      id: '/library/detail/$progressId'
      path: '/library/detail/$progressId'
      fullPath: '/library/detail/$progressId'
      preLoaderRoute: typeof LibraryDetailProgressIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/data/anime/': {
      id: '/data/anime/'
      path: '/data/anime'
      fullPath: '/data/anime'
      preLoaderRoute: typeof DataAnimeIndexImport
      parentRoute: typeof rootRoute
    }
    '/search/anime/': {
      id: '/search/anime/'
      path: '/search/anime'
      fullPath: '/search/anime'
      preLoaderRoute: typeof SearchAnimeIndexImport
      parentRoute: typeof rootRoute
    }
    '/edit/new/anime/': {
      id: '/edit/new/anime/'
      path: '/edit/new/anime'
      fullPath: '/edit/new/anime'
      preLoaderRoute: typeof EditNewAnimeIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/edit': typeof EditIndexRoute
  '/library': typeof LibraryIndexRoute
  '/data': typeof DataIndexLazyRoute
  '/getstarted': typeof GetstartedIndexLazyRoute
  '/login': typeof LoginIndexLazyRoute
  '/logout': typeof LogoutIndexLazyRoute
  '/search': typeof SearchIndexLazyRoute
  '/signup': typeof SignupIndexLazyRoute
  '/contents/anime/$animeId': typeof ContentsAnimeAnimeIdLazyRoute
  '/edit/anime/$animeId': typeof EditAnimeAnimeIdLazyRoute
  '/library/detail/$progressId': typeof LibraryDetailProgressIdLazyRoute
  '/data/anime': typeof DataAnimeIndexRoute
  '/search/anime': typeof SearchAnimeIndexRoute
  '/edit/new/anime': typeof EditNewAnimeIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/edit': typeof EditIndexRoute
  '/library': typeof LibraryIndexRoute
  '/data': typeof DataIndexLazyRoute
  '/getstarted': typeof GetstartedIndexLazyRoute
  '/login': typeof LoginIndexLazyRoute
  '/logout': typeof LogoutIndexLazyRoute
  '/search': typeof SearchIndexLazyRoute
  '/signup': typeof SignupIndexLazyRoute
  '/contents/anime/$animeId': typeof ContentsAnimeAnimeIdLazyRoute
  '/edit/anime/$animeId': typeof EditAnimeAnimeIdLazyRoute
  '/library/detail/$progressId': typeof LibraryDetailProgressIdLazyRoute
  '/data/anime': typeof DataAnimeIndexRoute
  '/search/anime': typeof SearchAnimeIndexRoute
  '/edit/new/anime': typeof EditNewAnimeIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/edit/': typeof EditIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/data/': typeof DataIndexLazyRoute
  '/getstarted/': typeof GetstartedIndexLazyRoute
  '/login/': typeof LoginIndexLazyRoute
  '/logout/': typeof LogoutIndexLazyRoute
  '/search/': typeof SearchIndexLazyRoute
  '/signup/': typeof SignupIndexLazyRoute
  '/contents/anime/$animeId': typeof ContentsAnimeAnimeIdLazyRoute
  '/edit/anime/$animeId': typeof EditAnimeAnimeIdLazyRoute
  '/library/detail/$progressId': typeof LibraryDetailProgressIdLazyRoute
  '/data/anime/': typeof DataAnimeIndexRoute
  '/search/anime/': typeof SearchAnimeIndexRoute
  '/edit/new/anime/': typeof EditNewAnimeIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/edit'
    | '/library'
    | '/data'
    | '/getstarted'
    | '/login'
    | '/logout'
    | '/search'
    | '/signup'
    | '/contents/anime/$animeId'
    | '/edit/anime/$animeId'
    | '/library/detail/$progressId'
    | '/data/anime'
    | '/search/anime'
    | '/edit/new/anime'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/edit'
    | '/library'
    | '/data'
    | '/getstarted'
    | '/login'
    | '/logout'
    | '/search'
    | '/signup'
    | '/contents/anime/$animeId'
    | '/edit/anime/$animeId'
    | '/library/detail/$progressId'
    | '/data/anime'
    | '/search/anime'
    | '/edit/new/anime'
  id:
    | '__root__'
    | '/'
    | '/edit/'
    | '/library/'
    | '/data/'
    | '/getstarted/'
    | '/login/'
    | '/logout/'
    | '/search/'
    | '/signup/'
    | '/contents/anime/$animeId'
    | '/edit/anime/$animeId'
    | '/library/detail/$progressId'
    | '/data/anime/'
    | '/search/anime/'
    | '/edit/new/anime/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditIndexRoute: typeof EditIndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  DataIndexLazyRoute: typeof DataIndexLazyRoute
  GetstartedIndexLazyRoute: typeof GetstartedIndexLazyRoute
  LoginIndexLazyRoute: typeof LoginIndexLazyRoute
  LogoutIndexLazyRoute: typeof LogoutIndexLazyRoute
  SearchIndexLazyRoute: typeof SearchIndexLazyRoute
  SignupIndexLazyRoute: typeof SignupIndexLazyRoute
  ContentsAnimeAnimeIdLazyRoute: typeof ContentsAnimeAnimeIdLazyRoute
  EditAnimeAnimeIdLazyRoute: typeof EditAnimeAnimeIdLazyRoute
  LibraryDetailProgressIdLazyRoute: typeof LibraryDetailProgressIdLazyRoute
  DataAnimeIndexRoute: typeof DataAnimeIndexRoute
  SearchAnimeIndexRoute: typeof SearchAnimeIndexRoute
  EditNewAnimeIndexLazyRoute: typeof EditNewAnimeIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditIndexRoute: EditIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  DataIndexLazyRoute: DataIndexLazyRoute,
  GetstartedIndexLazyRoute: GetstartedIndexLazyRoute,
  LoginIndexLazyRoute: LoginIndexLazyRoute,
  LogoutIndexLazyRoute: LogoutIndexLazyRoute,
  SearchIndexLazyRoute: SearchIndexLazyRoute,
  SignupIndexLazyRoute: SignupIndexLazyRoute,
  ContentsAnimeAnimeIdLazyRoute: ContentsAnimeAnimeIdLazyRoute,
  EditAnimeAnimeIdLazyRoute: EditAnimeAnimeIdLazyRoute,
  LibraryDetailProgressIdLazyRoute: LibraryDetailProgressIdLazyRoute,
  DataAnimeIndexRoute: DataAnimeIndexRoute,
  SearchAnimeIndexRoute: SearchAnimeIndexRoute,
  EditNewAnimeIndexLazyRoute: EditNewAnimeIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/edit/",
        "/library/",
        "/data/",
        "/getstarted/",
        "/login/",
        "/logout/",
        "/search/",
        "/signup/",
        "/contents/anime/$animeId",
        "/edit/anime/$animeId",
        "/library/detail/$progressId",
        "/data/anime/",
        "/search/anime/",
        "/edit/new/anime/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/edit/": {
      "filePath": "edit/index.tsx"
    },
    "/library/": {
      "filePath": "library/index.tsx"
    },
    "/data/": {
      "filePath": "data/index.lazy.tsx"
    },
    "/getstarted/": {
      "filePath": "getstarted/index.lazy.tsx"
    },
    "/login/": {
      "filePath": "login/index.lazy.tsx"
    },
    "/logout/": {
      "filePath": "logout/index.lazy.tsx"
    },
    "/search/": {
      "filePath": "search/index.lazy.tsx"
    },
    "/signup/": {
      "filePath": "signup/index.lazy.tsx"
    },
    "/contents/anime/$animeId": {
      "filePath": "contents/anime/$animeId.lazy.tsx"
    },
    "/edit/anime/$animeId": {
      "filePath": "edit/anime/$animeId.lazy.tsx"
    },
    "/library/detail/$progressId": {
      "filePath": "library/detail/$progressId.lazy.tsx"
    },
    "/data/anime/": {
      "filePath": "data/anime/index.tsx"
    },
    "/search/anime/": {
      "filePath": "search/anime/index.tsx"
    },
    "/edit/new/anime/": {
      "filePath": "edit/new/anime/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
