/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LibraryRouteImport } from './routes/library/route'
import { Route as IndexImport } from './routes/index'
import { Route as EditIndexImport } from './routes/edit/index'
import { Route as LibraryStartedIndexImport } from './routes/library/started/index'
import { Route as LibraryNotstartedIndexImport } from './routes/library/notstarted/index'
import { Route as LibraryCompletedIndexImport } from './routes/library/completed/index'

// Create Virtual Routes

const SignupIndexLazyImport = createFileRoute('/signup/')()
const SearchIndexLazyImport = createFileRoute('/search/')()
const LogoutIndexLazyImport = createFileRoute('/logout/')()
const LoginIndexLazyImport = createFileRoute('/login/')()
const GetstartedIndexLazyImport = createFileRoute('/getstarted/')()
const DataIndexLazyImport = createFileRoute('/data/')()
const SearchAnimeIndexLazyImport = createFileRoute('/search/anime/')()
const DataAnimeIndexLazyImport = createFileRoute('/data/anime/')()
const EditAnimeAnimeIdLazyImport = createFileRoute('/edit/anime/$animeId')()
const ContentsAnimeAnimeIdLazyImport = createFileRoute(
  '/contents/anime/$animeId',
)()
const EditNewAnimeIndexLazyImport = createFileRoute('/edit/new/anime/')()
const LibraryStartedDetailProgressIdLazyImport = createFileRoute(
  '/library/started/detail/$progressId',
)()

// Create/Update Routes

const LibraryRouteRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SignupIndexLazyRoute = SignupIndexLazyImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signup/index.lazy').then((d) => d.Route))

const SearchIndexLazyRoute = SearchIndexLazyImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/search/index.lazy').then((d) => d.Route))

const LogoutIndexLazyRoute = LogoutIndexLazyImport.update({
  id: '/logout/',
  path: '/logout/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/logout/index.lazy').then((d) => d.Route))

const LoginIndexLazyRoute = LoginIndexLazyImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login/index.lazy').then((d) => d.Route))

const GetstartedIndexLazyRoute = GetstartedIndexLazyImport.update({
  id: '/getstarted/',
  path: '/getstarted/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/getstarted/index.lazy').then((d) => d.Route),
)

const DataIndexLazyRoute = DataIndexLazyImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/data/index.lazy').then((d) => d.Route))

const EditIndexRoute = EditIndexImport.update({
  id: '/edit/',
  path: '/edit/',
  getParentRoute: () => rootRoute,
} as any)

const SearchAnimeIndexLazyRoute = SearchAnimeIndexLazyImport.update({
  id: '/search/anime/',
  path: '/search/anime/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/search/anime/index.lazy').then((d) => d.Route),
)

const DataAnimeIndexLazyRoute = DataAnimeIndexLazyImport.update({
  id: '/data/anime/',
  path: '/data/anime/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/data/anime/index.lazy').then((d) => d.Route),
)

const LibraryStartedIndexRoute = LibraryStartedIndexImport.update({
  id: '/started/',
  path: '/started/',
  getParentRoute: () => LibraryRouteRoute,
} as any)

const LibraryNotstartedIndexRoute = LibraryNotstartedIndexImport.update({
  id: '/notstarted/',
  path: '/notstarted/',
  getParentRoute: () => LibraryRouteRoute,
} as any)

const LibraryCompletedIndexRoute = LibraryCompletedIndexImport.update({
  id: '/completed/',
  path: '/completed/',
  getParentRoute: () => LibraryRouteRoute,
} as any)

const EditAnimeAnimeIdLazyRoute = EditAnimeAnimeIdLazyImport.update({
  id: '/edit/anime/$animeId',
  path: '/edit/anime/$animeId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/edit/anime/$animeId.lazy').then((d) => d.Route),
)

const ContentsAnimeAnimeIdLazyRoute = ContentsAnimeAnimeIdLazyImport.update({
  id: '/contents/anime/$animeId',
  path: '/contents/anime/$animeId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/contents/anime/$animeId.lazy').then((d) => d.Route),
)

const EditNewAnimeIndexLazyRoute = EditNewAnimeIndexLazyImport.update({
  id: '/edit/new/anime/',
  path: '/edit/new/anime/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/edit/new/anime/index.lazy').then((d) => d.Route),
)

const LibraryStartedDetailProgressIdLazyRoute =
  LibraryStartedDetailProgressIdLazyImport.update({
    id: '/started/detail/$progressId',
    path: '/started/detail/$progressId',
    getParentRoute: () => LibraryRouteRoute,
  } as any).lazy(() =>
    import('./routes/library/started/detail/$progressId.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRoute
    }
    '/edit/': {
      id: '/edit/'
      path: '/edit'
      fullPath: '/edit'
      preLoaderRoute: typeof EditIndexImport
      parentRoute: typeof rootRoute
    }
    '/data/': {
      id: '/data/'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/getstarted/': {
      id: '/getstarted/'
      path: '/getstarted'
      fullPath: '/getstarted'
      preLoaderRoute: typeof GetstartedIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/logout/': {
      id: '/logout/'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/contents/anime/$animeId': {
      id: '/contents/anime/$animeId'
      path: '/contents/anime/$animeId'
      fullPath: '/contents/anime/$animeId'
      preLoaderRoute: typeof ContentsAnimeAnimeIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/edit/anime/$animeId': {
      id: '/edit/anime/$animeId'
      path: '/edit/anime/$animeId'
      fullPath: '/edit/anime/$animeId'
      preLoaderRoute: typeof EditAnimeAnimeIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/library/completed/': {
      id: '/library/completed/'
      path: '/completed'
      fullPath: '/library/completed'
      preLoaderRoute: typeof LibraryCompletedIndexImport
      parentRoute: typeof LibraryRouteImport
    }
    '/library/notstarted/': {
      id: '/library/notstarted/'
      path: '/notstarted'
      fullPath: '/library/notstarted'
      preLoaderRoute: typeof LibraryNotstartedIndexImport
      parentRoute: typeof LibraryRouteImport
    }
    '/library/started/': {
      id: '/library/started/'
      path: '/started'
      fullPath: '/library/started'
      preLoaderRoute: typeof LibraryStartedIndexImport
      parentRoute: typeof LibraryRouteImport
    }
    '/data/anime/': {
      id: '/data/anime/'
      path: '/data/anime'
      fullPath: '/data/anime'
      preLoaderRoute: typeof DataAnimeIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/search/anime/': {
      id: '/search/anime/'
      path: '/search/anime'
      fullPath: '/search/anime'
      preLoaderRoute: typeof SearchAnimeIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/library/started/detail/$progressId': {
      id: '/library/started/detail/$progressId'
      path: '/started/detail/$progressId'
      fullPath: '/library/started/detail/$progressId'
      preLoaderRoute: typeof LibraryStartedDetailProgressIdLazyImport
      parentRoute: typeof LibraryRouteImport
    }
    '/edit/new/anime/': {
      id: '/edit/new/anime/'
      path: '/edit/new/anime'
      fullPath: '/edit/new/anime'
      preLoaderRoute: typeof EditNewAnimeIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface LibraryRouteRouteChildren {
  LibraryCompletedIndexRoute: typeof LibraryCompletedIndexRoute
  LibraryNotstartedIndexRoute: typeof LibraryNotstartedIndexRoute
  LibraryStartedIndexRoute: typeof LibraryStartedIndexRoute
  LibraryStartedDetailProgressIdLazyRoute: typeof LibraryStartedDetailProgressIdLazyRoute
}

const LibraryRouteRouteChildren: LibraryRouteRouteChildren = {
  LibraryCompletedIndexRoute: LibraryCompletedIndexRoute,
  LibraryNotstartedIndexRoute: LibraryNotstartedIndexRoute,
  LibraryStartedIndexRoute: LibraryStartedIndexRoute,
  LibraryStartedDetailProgressIdLazyRoute:
    LibraryStartedDetailProgressIdLazyRoute,
}

const LibraryRouteRouteWithChildren = LibraryRouteRoute._addFileChildren(
  LibraryRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRouteRouteWithChildren
  '/edit': typeof EditIndexRoute
  '/data': typeof DataIndexLazyRoute
  '/getstarted': typeof GetstartedIndexLazyRoute
  '/login': typeof LoginIndexLazyRoute
  '/logout': typeof LogoutIndexLazyRoute
  '/search': typeof SearchIndexLazyRoute
  '/signup': typeof SignupIndexLazyRoute
  '/contents/anime/$animeId': typeof ContentsAnimeAnimeIdLazyRoute
  '/edit/anime/$animeId': typeof EditAnimeAnimeIdLazyRoute
  '/library/completed': typeof LibraryCompletedIndexRoute
  '/library/notstarted': typeof LibraryNotstartedIndexRoute
  '/library/started': typeof LibraryStartedIndexRoute
  '/data/anime': typeof DataAnimeIndexLazyRoute
  '/search/anime': typeof SearchAnimeIndexLazyRoute
  '/library/started/detail/$progressId': typeof LibraryStartedDetailProgressIdLazyRoute
  '/edit/new/anime': typeof EditNewAnimeIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRouteRouteWithChildren
  '/edit': typeof EditIndexRoute
  '/data': typeof DataIndexLazyRoute
  '/getstarted': typeof GetstartedIndexLazyRoute
  '/login': typeof LoginIndexLazyRoute
  '/logout': typeof LogoutIndexLazyRoute
  '/search': typeof SearchIndexLazyRoute
  '/signup': typeof SignupIndexLazyRoute
  '/contents/anime/$animeId': typeof ContentsAnimeAnimeIdLazyRoute
  '/edit/anime/$animeId': typeof EditAnimeAnimeIdLazyRoute
  '/library/completed': typeof LibraryCompletedIndexRoute
  '/library/notstarted': typeof LibraryNotstartedIndexRoute
  '/library/started': typeof LibraryStartedIndexRoute
  '/data/anime': typeof DataAnimeIndexLazyRoute
  '/search/anime': typeof SearchAnimeIndexLazyRoute
  '/library/started/detail/$progressId': typeof LibraryStartedDetailProgressIdLazyRoute
  '/edit/new/anime': typeof EditNewAnimeIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/library': typeof LibraryRouteRouteWithChildren
  '/edit/': typeof EditIndexRoute
  '/data/': typeof DataIndexLazyRoute
  '/getstarted/': typeof GetstartedIndexLazyRoute
  '/login/': typeof LoginIndexLazyRoute
  '/logout/': typeof LogoutIndexLazyRoute
  '/search/': typeof SearchIndexLazyRoute
  '/signup/': typeof SignupIndexLazyRoute
  '/contents/anime/$animeId': typeof ContentsAnimeAnimeIdLazyRoute
  '/edit/anime/$animeId': typeof EditAnimeAnimeIdLazyRoute
  '/library/completed/': typeof LibraryCompletedIndexRoute
  '/library/notstarted/': typeof LibraryNotstartedIndexRoute
  '/library/started/': typeof LibraryStartedIndexRoute
  '/data/anime/': typeof DataAnimeIndexLazyRoute
  '/search/anime/': typeof SearchAnimeIndexLazyRoute
  '/library/started/detail/$progressId': typeof LibraryStartedDetailProgressIdLazyRoute
  '/edit/new/anime/': typeof EditNewAnimeIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/edit'
    | '/data'
    | '/getstarted'
    | '/login'
    | '/logout'
    | '/search'
    | '/signup'
    | '/contents/anime/$animeId'
    | '/edit/anime/$animeId'
    | '/library/completed'
    | '/library/notstarted'
    | '/library/started'
    | '/data/anime'
    | '/search/anime'
    | '/library/started/detail/$progressId'
    | '/edit/new/anime'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/library'
    | '/edit'
    | '/data'
    | '/getstarted'
    | '/login'
    | '/logout'
    | '/search'
    | '/signup'
    | '/contents/anime/$animeId'
    | '/edit/anime/$animeId'
    | '/library/completed'
    | '/library/notstarted'
    | '/library/started'
    | '/data/anime'
    | '/search/anime'
    | '/library/started/detail/$progressId'
    | '/edit/new/anime'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/edit/'
    | '/data/'
    | '/getstarted/'
    | '/login/'
    | '/logout/'
    | '/search/'
    | '/signup/'
    | '/contents/anime/$animeId'
    | '/edit/anime/$animeId'
    | '/library/completed/'
    | '/library/notstarted/'
    | '/library/started/'
    | '/data/anime/'
    | '/search/anime/'
    | '/library/started/detail/$progressId'
    | '/edit/new/anime/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRouteRoute: typeof LibraryRouteRouteWithChildren
  EditIndexRoute: typeof EditIndexRoute
  DataIndexLazyRoute: typeof DataIndexLazyRoute
  GetstartedIndexLazyRoute: typeof GetstartedIndexLazyRoute
  LoginIndexLazyRoute: typeof LoginIndexLazyRoute
  LogoutIndexLazyRoute: typeof LogoutIndexLazyRoute
  SearchIndexLazyRoute: typeof SearchIndexLazyRoute
  SignupIndexLazyRoute: typeof SignupIndexLazyRoute
  ContentsAnimeAnimeIdLazyRoute: typeof ContentsAnimeAnimeIdLazyRoute
  EditAnimeAnimeIdLazyRoute: typeof EditAnimeAnimeIdLazyRoute
  DataAnimeIndexLazyRoute: typeof DataAnimeIndexLazyRoute
  SearchAnimeIndexLazyRoute: typeof SearchAnimeIndexLazyRoute
  EditNewAnimeIndexLazyRoute: typeof EditNewAnimeIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRouteRoute: LibraryRouteRouteWithChildren,
  EditIndexRoute: EditIndexRoute,
  DataIndexLazyRoute: DataIndexLazyRoute,
  GetstartedIndexLazyRoute: GetstartedIndexLazyRoute,
  LoginIndexLazyRoute: LoginIndexLazyRoute,
  LogoutIndexLazyRoute: LogoutIndexLazyRoute,
  SearchIndexLazyRoute: SearchIndexLazyRoute,
  SignupIndexLazyRoute: SignupIndexLazyRoute,
  ContentsAnimeAnimeIdLazyRoute: ContentsAnimeAnimeIdLazyRoute,
  EditAnimeAnimeIdLazyRoute: EditAnimeAnimeIdLazyRoute,
  DataAnimeIndexLazyRoute: DataAnimeIndexLazyRoute,
  SearchAnimeIndexLazyRoute: SearchAnimeIndexLazyRoute,
  EditNewAnimeIndexLazyRoute: EditNewAnimeIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/library",
        "/edit/",
        "/data/",
        "/getstarted/",
        "/login/",
        "/logout/",
        "/search/",
        "/signup/",
        "/contents/anime/$animeId",
        "/edit/anime/$animeId",
        "/data/anime/",
        "/search/anime/",
        "/edit/new/anime/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/library": {
      "filePath": "library/route.tsx",
      "children": [
        "/library/completed/",
        "/library/notstarted/",
        "/library/started/",
        "/library/started/detail/$progressId"
      ]
    },
    "/edit/": {
      "filePath": "edit/index.tsx"
    },
    "/data/": {
      "filePath": "data/index.lazy.tsx"
    },
    "/getstarted/": {
      "filePath": "getstarted/index.lazy.tsx"
    },
    "/login/": {
      "filePath": "login/index.lazy.tsx"
    },
    "/logout/": {
      "filePath": "logout/index.lazy.tsx"
    },
    "/search/": {
      "filePath": "search/index.lazy.tsx"
    },
    "/signup/": {
      "filePath": "signup/index.lazy.tsx"
    },
    "/contents/anime/$animeId": {
      "filePath": "contents/anime/$animeId.lazy.tsx"
    },
    "/edit/anime/$animeId": {
      "filePath": "edit/anime/$animeId.lazy.tsx"
    },
    "/library/completed/": {
      "filePath": "library/completed/index.tsx",
      "parent": "/library"
    },
    "/library/notstarted/": {
      "filePath": "library/notstarted/index.tsx",
      "parent": "/library"
    },
    "/library/started/": {
      "filePath": "library/started/index.tsx",
      "parent": "/library"
    },
    "/data/anime/": {
      "filePath": "data/anime/index.lazy.tsx"
    },
    "/search/anime/": {
      "filePath": "search/anime/index.lazy.tsx"
    },
    "/library/started/detail/$progressId": {
      "filePath": "library/started/detail/$progressId.lazy.tsx",
      "parent": "/library"
    },
    "/edit/new/anime/": {
      "filePath": "edit/new/anime/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
